name: kics_check
on:
  pull_request:
    branches: [master]
  push: 
    branches: [master]
jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: KICS Github Action
        id: kics
        uses: Checkmarx/kics-github-action@v1.2
        with:
          path: 'terraform'
          output_path: 'results.sarif'
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'results.sarif'
