name: build
on:
  pull_request
jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Kics action
        id: kics
        uses: 
        with:
          directory: terraform/
